### ISSUE TITLE
Make templates more usable

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_lang#128]
Hi Jonathan

Made some xlsx template models with `wc_lang.io.Reader.create_template`, but they weren't usable. Need to unlock worksheets, show ribbon, & make the workbook writeable. All these problems using Excel 15.32 on MacOS High Sierra.

Using `obj_table` @ `d6b76d59d52f14680f5582de02c32811e8bc4e10`
Using `wc_lang` @ `8f8f1978ffaeeb43691dded31c039996963a68fa`

I'll just copy and empty an existing model. 

Thanks
Arthur

**Comment by jonrkarr** [comment]
The templates are writable on Excel 2010/Windows and WPS/Linux:
- Writing content cells
- Adding and deleting rows
- Selecting cells

The protection discourages these actions:
- Adding and deleting columns
- Formatting cells
- Inserting hyperlinks, pivot tables, and other objects that `obj_tables` would ignore
- Sorting and changing auto filtering (these don't need to be disabled, but Excel doesn't allow these to be controlled separately from the above protections)

To make this more flexible, I have added arguments to disable the protection. I added these arguments to `wc_utils`, `obj_tables`, `wc_lang`, and `wc_kb` including to the command-line programs and `obj_tables`' REST API.
```
obj-tables gen-template --unprotected examples/biochemical_models/schema.csv template.xlsx
wc-lang create-template --unprotected template.xlsx
```
