### ISSUE TITLE
Reduce redundancy in representation of dFBA Reactions

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_lang#129]
Including reverse links, these models and attributes define dFBA objectives now, where '(s)' indicates multiplicity:

    Submodel.dfba_obj - DfbaObjective
    Submodel.dfba_obj_reactions - DfbaObjReaction(s)

    DfbaObjectiveExpression.reactions - Reaction(s)
    DfbaObjectiveExpression.dfba_obj_reactions - DfbaObjReaction(s)
    DfbaObjectiveExpression.dfba_obj - DfbaObjective

    DfbaObjective.submodel - Submodel
    DfbaObjective.expression - DfbaObjectiveExpression

    DfbaObjSpecies.dfba_obj_reaction - DfbaObjReaction
    DfbaObjSpecies.species - Species(s)

    FluxBounds.reactions - Reaction(s)

    Reaction.flux_bounds - FluxBounds
    Reaction.dfba_obj_expression - DfbaObjectiveExpression

    DfbaObjReaction.submodel - Submodel
    DfbaObjReaction.dfba_obj_expression - DfbaObjectiveExpression
    DfbaObjReaction.dfba_obj_species - DfbaObjSpecies(s)

    Species.dfba_obj_species - DfbaObjSpecies(s)

I think it could be simplified by requiring that all reactions used in dFBA be written as `DfbaObjReactions`. This would require that reactions which both transform species and serve as the basis for objective(s) be duplicated. But it would substantially simplify the data model, and would be a net win. In addition, a `Submodel` can access its DfbaObjReaction(s) through its DfbaObjective (Submodel.dfba_obj.expression.dfba_obj_reactions) which eliminates a redundant attribute in `Submodel`. This would reduce the number of attribute definitions needed for the dFBA objectives from 8 to 6.

    Submodel.dfba_obj - DfbaObjective

    DfbaObjectiveExpression.dfba_obj_reactions - DfbaObjReaction(s)
    DfbaObjectiveExpression.dfba_obj - DfbaObjective

    DfbaObjective.submodel - Submodel
    DfbaObjective.expression - DfbaObjectiveExpression

    DfbaObjSpecies.dfba_obj_reaction - DfbaObjReaction
    DfbaObjSpecies.species - Species(s)

    FluxBounds.reactions - DfbaObjReaction(s)

    DfbaObjReaction.dfba_obj_expression - DfbaObjectiveExpression
    DfbaObjReaction.dfba_obj_species - DfbaObjSpecies(s)
    DfbaObjReaction.flux_bounds - FluxBounds

    Species.dfba_obj_species - DfbaObjSpecies(s)

**Comment by jonrkarr** [comment]
Closing this issue because there has been no further discussion.
