### ISSUE TITLE
counter intuitive get_species() VS get_species_types() behaviour

### ISSUE THREAD

**Issue by balazs1987** [KarrLab/wc_lang#16]
I have noticed a very counter intuitive behavior in the code:
- model.get_species_type() returns a ManytoOneRelatedManager, while 
- model.get_species() returns a list.

Given how these methods are called, I would have expected to get the same type of return. 

Unless there is a good reason not to do so, can we change so that get_species() also returns a Manager type object? The Manager comes with convenience methods (e.g. get(), get_or_create()) that I would like to use

**Comment by balazs1987** [comment]
ps.: same with model.get_reactions

**Comment by jonrkarr** [comment]
RelatedManager is a subclass of list.

**Comment by jonrkarr** [comment]
Fixed in b1bec925f51c8276c3afe217d4250e75867e40fb.

`get_*` convenience methods now return distinct lists that are difference from the related managers
