### ISSUE TITLE
Changing rate_law_utils to expression_utils

### ISSUE THREAD

**Issue by Ashwin-Srinivasan** [KarrLab/wc_lang#22]
Changing the name of the module rate_law_utils to expression_utils causes issues with importing rate_law_utils in wc_sim/multialgorithm/observables.py (and might cause issues in other files as well).

**Comment by jonrkarr** [comment]
If you want to change module, function, or attribute names, please
propagate these changes to the downstream dependencies.

**Comment by artgoldberg** [comment]
Fixed.
Sorry Ashwin & Jonathan, I made the changes to wc_sim but forgot to push them when I pushed wc_lang.
Also, I noticed that Circle did not run tests on the downstream dependencies when I pushed wc_lang. I've added details to that issue on karr_lab_build_utils
