### ISSUE TITLE
Add type attribute to Compartment

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_lang#40]
Types
- abstract
- physical (3D)

**Comment by artgoldberg** [comment]
I have done this and will push it when I've got the models migrated.
FYI, the types are 
- abstract
- biochemical

**Comment by jonrkarr** [comment]
Yes, I know. Just trying to keep track of changes.

I think we should rename `biochemical` to `physical_3d`. This is more
descriptive, more specific, and will allow for the possibility of 2d
compartments.

**Comment by artgoldberg** [comment]
OK.
