### ISSUE TITLE
allow concentration or abundance for initial conditions

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_lang#6]
Column for molecular amount
column for units

**Comment by jonrkarr** [comment]
While wc_lang should support amounts and concentrations, modelers should be encouraged to only use amounts for tightly controlled species (such as below) and Boolean-valued species:

- Chromosomes
- Nuclei
- Replication initiators such as DnaA
- Cytokinesis machinery such as FtsZ

**Comment by jonrkarr** [comment]
implemented in 34a784ee112e8529cc86fe633dfbf6c2353bb830
