### ISSUE TITLE
wc_lang.core.Parameter :: 'submodel' is an invalid keyword argument

### ISSUE THREAD

**Issue by aesundstrom** [KarrLab/wc_lang#7]
Parameter advertises argument "submodel" but actually expects "submodels", a list of Submodel.

In core.py :: 2171-2188:

class Parameter(obj_model.Model):
    """ Parameter
    Attributes:
        id (:obj:`str`): unique identifier per model/submodel
        name (:obj:`str`): name
        model (:obj:`Model`): model
        submodel (:obj:`Submodel`): submodel
        value (:obj:`float`): value
        units (:obj:`str`): units of value
        comments (:obj:`str`): comments
        references (:obj:`list` of `Reference`): references
    """
    id = SlugAttribute(unique=False)
    name = StringAttribute()
    model = ManyToOneAttribute(Model, related_name='parameters')
    submodels = ManyToManyAttribute(Submodel, related_name='parameters')
    value = FloatAttribute(min=0)
    units = StringAttribute()
    comments = LongStringAttribute()
    references = ManyToManyAttribute('Reference', related_name='parameters')

**Comment by jonrkarr** [comment]
Fixed
