### ISSUE TITLE
Better error messages for failing validation

### ISSUE THREAD

**Issue by balazs1987** [KarrLab/wc_lang#86]
When a reaction fails to validate, the program should tell the user which exact reaction is failing validation. Currently the output looks like:

/home/balazs/Desktop/obj_model/obj_model/io.py:193 IoWarning: Some data will not be written because objects are not valid:
  Reaction:
    'participants':
      Reaction is element imbalanced: H-400O-200

Instead of 'participants', it should print reaction ID

**Comment by jonrkarr** [comment]
Added ids to error messages. Implemented in obj_model.
